# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: WeaMyL
subtitle: Colaborare de cercetare între România și Norvegia
subsubtitle: schemei de granturi EEA și Norvegia
email:
description: >- # this means to ignore newlines until "baseurl:"
  Combining Machine Learning ...
# twitter_username: username
# github_username: username
repository: "metno/..."
title_separator: "-"
minimal_mistakes_skin: default
search: false
logo: "https://weamyl.met.no/assets/images/LogoMyLFinal-01.png"

# Build settings
markdown: kramdown
# theme: minimal-mistakes-jekyll
# theme: jekyll-theme-minimal
# them : mmistakes/minimal-mistakes@4.19.3
remote_theme: mmistakes/minimal-mistakes@4.19.3

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-17RV2YBYQ0"
    anonymize_ip: true

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "No One"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Nothing here."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"

footer:
  image: https://weamyl.met.no/assets/images/LogoMyLFinal-01.png
  image2: https://weamyl.met.no/assets/images/En2.png
  links:
    - label: "MET Norway"
      icon: "fas fa-fw fa-water"
      url: "https://met.no/"
    - label: "Babes-Bolyai University"
      icon: "fas fa-fw fa-university"
      url: "https://www.ubbcluj.ro/en/"
    - label: "Administrația Națională de Meteorologie"
      icon: "fas fa-fw fa-water"
      url: "https://www.meteoromania.ro/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      toc: true
      toc_icon: bars
      toc_label: "Contents"
      header:
        overlay_color: "#2073ac"
      sidebar:
        - title: ""
          nav: page_links

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
